# Generated by Django 4.2.4 on 2023-08-30 21:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TraficLightDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_color', models.CharField(max_length=5)),
                ('current_date', models.DateTimeField()),
                ('traffic_light', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='traffic_light.trafficlight')),
            ],
        ),
    ]
